# Generated by Django 3.2.20 on 2023-10-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gahana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OQOO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d2', models.BigIntegerField()),
                ('d3', models.CharField(blank=True, max_length=100, null=True)),
                ('d4', models.BigIntegerField(blank=True, null=True)),
                ('f2', models.EmailField(blank=True, max_length=254, null=True)),
                ('f3', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
